const C=window.APP_CONFIG;let db=null,store={restaurant:null,categories:[],products:[],tables:[],orders:[]};let cart=[];let currentCat='all';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=n=>`${Number(n||0).toFixed(0)} ${C.currency}`;
function toast(x){$('#toast').innerHTML=`<div class="fixed bottom-5 left-1/2 -translate-x-1/2 z-[100] rounded-2xl bg-black text-white px-5 py-3 shadow-2xl">${esc(x)}</div>`;setTimeout(()=>$('#toast').innerHTML='',2500)}
function persist(){localStorage.setItem('ros_v2_demo',JSON.stringify(store))}
function seed(){store.restaurant={...C.demoRestaurant};store.categories=structuredClone(C.demoCategories);store.products=structuredClone(C.demoProducts);store.tables=Array.from({length:30},(_,i)=>({id:'demo-t'+(i+1),restaurant_id:store.restaurant.id,table_number:i+1,active:true}));store.orders=[]}
const THEMES={
  obsidian:{name:'Obsidian Gold',accent:'#D4AF37',bg:'#0D0E10',surface:'#17191D',surface2:'#202329',text:'#F6F1E7',muted:'#A9A39A'},
  emerald:{name:'Emerald Noir',accent:'#3BB78F',bg:'#071311',surface:'#101D1A',surface2:'#172824',text:'#F1F7F3',muted:'#A7B8B1'},
  burgundy:{name:'Burgundy Luxe',accent:'#C85C62',bg:'#160B0D',surface:'#241316',surface2:'#31191D',text:'#FFF2F1',muted:'#BDA8A9'},
  navy:{name:'Midnight Navy',accent:'#6D8CFF',bg:'#080D18',surface:'#121A2A',surface2:'#19233A',text:'#F1F4FF',muted:'#AAB4CC'},
  sand:{name:'Champagne Sand',accent:'#B58A52',bg:'#17130E',surface:'#231D15',surface2:'#30271B',text:'#FFF8EC',muted:'#C7B9A3'},
  plum:{name:'Royal Plum',accent:'#B07BE8',bg:'#110B18',surface:'#1D1428',surface2:'#281B38',text:'#FAF3FF',muted:'#BBAAC7'}
};
function theme(){const c=store.restaurant?.primary_color||C.defaultTheme;const palette=Object.values(THEMES).find(x=>x.accent.toLowerCase()===String(c).toLowerCase())||THEMES.obsidian;document.documentElement.style.setProperty('--brand',c);document.documentElement.style.setProperty('--bg',palette.bg);document.documentElement.style.setProperty('--surface',palette.surface);document.documentElement.style.setProperty('--surface2',palette.surface2);document.documentElement.style.setProperty('--text',palette.text);document.documentElement.style.setProperty('--muted',palette.muted);document.body.style.background=palette.bg;document.body.style.color=palette.text}
function applyThemeColor(v){store.restaurant.primary_color=v;theme();renderMenu()}
async function loadSupabase(){const r=await db.from('restaurants').select('*').eq('slug',C.restaurantSlug).maybeSingle();if(r.error)throw r.error;if(!r.data){store={restaurant:null,categories:[],products:[],tables:[],orders:[]};return false}store.restaurant=r.data;for(const k of ['categories','products','tables']){const q=await db.from(k).select('*').eq('restaurant_id',r.data.id).order(k==='tables'?'table_number':'sort_order');if(q.error)throw q.error;store[k]=q.data||[]}const {data:{session}}=await db.auth.getSession();if(session){const o=await db.from('orders').select('*').eq('restaurant_id',r.data.id).order('created_at',{ascending:false}).limit(100);if(o.error)throw o.error;store.orders=o.data||[]}else store.orders=[];return true}
function showFatal(message){const appEl=$('#app');if(appEl)appEl.innerHTML=`<main style="min-height:100vh;display:grid;place-items:center;padding:24px;background:#f6f6f3;font-family:Cairo,Arial,sans-serif"><div style="max-width:520px;background:#fff;border-radius:24px;padding:28px;text-align:center;box-shadow:0 10px 40px #0001"><h1 style="font-size:26px;font-weight:800;margin:0 0 10px">تعذر تشغيل الموقع</h1><p style="color:#666;line-height:1.8;margin:0">${esc(message)}</p><button onclick="location.reload()" style="margin-top:18px;background:#111;color:#fff;border:0;border-radius:14px;padding:12px 22px;font-weight:700">إعادة المحاولة</button></div></main>`}
async function init(){try{if(C.mode==='supabase'&&C.supabaseUrl&&C.supabaseAnonKey){if(!window.supabase||typeof window.supabase.createClient!=='function'){showFatal('مكتبة Supabase لم يتم تحميلها. افتح الموقع مرة أخرى أو جرّب Chrome.');return}db=window.supabase.createClient(C.supabaseUrl,C.supabaseAnonKey);window.rosDb=db;try{const ok=await loadSupabase();if(!ok)toast('لم يتم إنشاء المطعم بعد — افتح لوحة الإدارة لإنشائه')}catch(e){console.error(e);seed();toast('تعذر الاتصال بـ Supabase — تم تشغيل نسخة العرض المحلية')}}else{seed()}renderRouter()}catch(e){console.error(e);showFatal('حدث خطأ غير متوقع أثناء تشغيل الموقع: '+(e?.message||e))}}
function renderRouter(){theme();const p=location.hash||'#menu';if(p==='#admin'||p.startsWith('#admin/'))renderAdmin();else renderMenu()}
window.addEventListener('hashchange',renderRouter);
function tableFromUrl(){const t=new URLSearchParams(location.search).get('table');if(!t||!/^[0-9]+$/.test(t))return null;const n=Number(t);return store.tables.some(x=>Number(x.table_number)===n&&x.active)?String(n):null}
function renderMenu(){if(!store.restaurant){$('#app').innerHTML=`<main class="min-h-screen grid place-items-center p-6 luxury-page"><div class="lux-card rounded-3xl p-7 max-w-md text-center"><h1 class="text-2xl font-extrabold">المطعم غير مُنشأ بعد</h1><p class="mt-2" style="color:var(--muted)">بيانات المطعم غير متاحة حاليًا.</p></div></main>`;return}theme();const table=tableFromUrl();$('#app').innerHTML=`<div class="min-h-screen luxury-page"><header class="sticky top-0 z-30 luxury-header"><div class="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between gap-3"><div class="flex items-center gap-3 min-w-0"><div class="brand-logo">${esc(store.restaurant.logo||'🍽️')}</div><div class="min-w-0"><div class="font-extrabold text-lg truncate">${esc(store.restaurant.name)}</div><div class="text-xs" style="color:var(--muted)">${table?'حضرتك شرفتنا على — الطاولة '+esc(table):'قائمة رقمية • اطلب من مكانك'}</div></div></div><button onclick="openCart()" class="cart-btn">السلة <span id="cartCount">0</span></button></div></header><main class="max-w-6xl mx-auto px-4 py-5"><section class="lux-hero"><div class="hero-glow"></div><div class="relative z-10"><div class="eyebrow">${table?'DINE-IN EXPERIENCE':'DIGITAL MENU'}</div><h1>طعم يستحق التجربة.</h1><p>اختار طلبك بسهولة واستمتع بتجربة مطعم أكثر أناقة، أسرع، وبدون انتظار.</p><div class="hero-meta"><span>✦ جودة</span><span>✦ سرعة</span><span>✦ تجربة مميزة</span></div></div></section><div id="cats" class="flex gap-2 overflow-auto pb-4 pt-1 luxury-scroll"></div><div id="products" class="grid sm:grid-cols-2 lg:grid-cols-3 gap-5"></div></main></div><div id="modal"></div>`;renderCategories();renderProducts();updateCart()}
function renderCategories(){const cats=[{id:'all',name:'الكل'},...store.categories];$('#cats').innerHTML=cats.map(c=>`<button onclick="currentCat='${c.id}';renderCategories();renderProducts()" class="cat-pill ${currentCat===c.id?'active':''}">${esc(c.name)}</button>`).join('')}
function renderProducts(){const list=store.products.filter(p=>p.available&&(currentCat==='all'||p.category_id===currentCat));$('#products').innerHTML=list.length?list.map(p=>`<article class="product-card-lux"><div class="product-image-wrap"><img src="${esc(p.image_url||'')}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none'"><span class="price-chip">${money(p.price)}</span></div><div class="p-4"><div class="font-extrabold text-lg">${esc(p.name)}</div><div class="text-sm min-h-10 mt-1" style="color:var(--muted)">${esc(p.description)}</div><div class="flex items-center justify-between mt-4"><span class="text-xs" style="color:var(--muted)">جاهز للطلب</span><button onclick="add('${p.id}')" class="add-btn">أضف للسلة</button></div></div></article>`).join(''):'<div class="col-span-full text-center py-16" style="color:var(--muted)">لا توجد منتجات متاحة في هذا القسم حاليًا.</div>'}