-- Restaurant OS V8: single-restaurant delivery + GPS extension
-- Run this ONCE in the SAME Supabase project used by V8.

create extension if not exists pgcrypto;

alter table public.orders add column if not exists tracking_token uuid;
alter table public.orders add column if not exists customer_lat double precision;
alter table public.orders add column if not exists customer_lng double precision;
update public.orders set tracking_token = gen_random_uuid() where tracking_token is null;
alter table public.orders alter column tracking_token set default gen_random_uuid();
create unique index if not exists orders_tracking_token_uidx on public.orders(tracking_token) where tracking_token is not null;
create index if not exists orders_restaurant_status_idx on public.orders(restaurant_id,status,created_at desc);

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  name text not null,
  phone text,
  access_token uuid not null unique default gen_random_uuid(),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists drivers_restaurant_idx on public.drivers(restaurant_id,active);

create table if not exists public.delivery_orders (
  order_id uuid primary key references public.orders(id) on delete cascade,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  driver_id uuid references public.drivers(id) on delete set null,
  status text not null default 'unassigned' check (status in ('unassigned','assigned','accepted','picked_up','out_for_delivery','delivered','cancelled')),
  assigned_at timestamptz,
  accepted_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists delivery_orders_restaurant_idx on public.delivery_orders(restaurant_id,status,updated_at desc);
create index if not exists delivery_orders_driver_idx on public.delivery_orders(driver_id,status,updated_at desc);

create table if not exists public.driver_locations (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  driver_id uuid not null references public.drivers(id) on delete cascade,
  order_id uuid references public.orders(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy double precision,
  recorded_at timestamptz not null default now()
);
create index if not exists driver_locations_order_time_idx on public.driver_locations(order_id,recorded_at desc);
create index if not exists driver_locations_driver_time_idx on public.driver_locations(driver_id,recorded_at desc);

alter table public.drivers enable row level security;
alter table public.delivery_orders enable row level security;
alter table public.driver_locations enable row level security;

drop policy if exists drivers_owner_all on public.drivers;
create policy drivers_owner_all on public.drivers for all to authenticated
using (exists (select 1 from public.restaurants r where r.id=drivers.restaurant_id and r.owner_id=auth.uid()))
with check (exists (select 1 from public.restaurants r where r.id=drivers.restaurant_id and r.owner_id=auth.uid()));

drop policy if exists delivery_orders_owner_all on public.delivery_orders;
create policy delivery_orders_owner_all on public.delivery_orders for all to authenticated
using (exists (select 1 from public.restaurants r where r.id=delivery_orders.restaurant_id and r.owner_id=auth.uid()))
with check (exists (select 1 from public.restaurants r where r.id=delivery_orders.restaurant_id and r.owner_id=auth.uid()));

drop policy if exists driver_locations_owner_select on public.driver_locations;
create policy driver_locations_owner_select on public.driver_locations for select to authenticated
using (exists (select 1 from public.restaurants r where r.id=driver_locations.restaurant_id and r.owner_id=auth.uid()));

create or replace function public.create_delivery_order(
  p_restaurant_id uuid,
  p_customer_name text,
  p_customer_phone text,
  p_address text,
  p_payment_method text,
  p_items jsonb,
  p_customer_lat double precision default null,
  p_customer_lng double precision default null
)
returns table(order_id uuid, tracking_token uuid, total numeric)
language plpgsql security definer set search_path=public
as $$
declare
  v_order_id uuid; v_token uuid:=gen_random_uuid(); v_total numeric:=0; v_item jsonb; v_product record; v_qty integer;
begin
  if p_restaurant_id is null then raise exception 'restaurant_required'; end if;
  if coalesce(trim(p_customer_name),'')='' then raise exception 'customer_name_required'; end if;
  if coalesce(trim(p_customer_phone),'')='' then raise exception 'customer_phone_required'; end if;
  if coalesce(trim(p_address),'')='' then raise exception 'address_required'; end if;
  if p_payment_method not in ('cash','vodafone') then raise exception 'invalid_payment_method'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items)=0 then raise exception 'items_required'; end if;
  for v_item in select value from jsonb_array_elements(p_items) loop
    v_qty:=greatest(1,least(99,coalesce((v_item->>'quantity')::integer,1)));
    select id,name,price,available into v_product from public.products where id=(v_item->>'product_id')::uuid and restaurant_id=p_restaurant_id and available=true;
    if not found then raise exception 'invalid_product'; end if;
    v_total:=v_total+(v_product.price*v_qty);
  end loop;
  insert into public.orders(restaurant_id,table_id,table_number,order_type,customer_name,customer_phone,address,payment_method,total,items,status,tracking_token,customer_lat,customer_lng)
  values(p_restaurant_id,null,null,'delivery',trim(p_customer_name),trim(p_customer_phone),trim(p_address),p_payment_method,v_total,p_items,'new',v_token,p_customer_lat,p_customer_lng)
  returning id into v_order_id;
  insert into public.delivery_orders(order_id,restaurant_id,status) values(v_order_id,p_restaurant_id,'unassigned');
  return query select v_order_id,v_token,v_total;
end;
$$;
revoke all on function public.create_delivery_order(uuid,text,text,text,text,jsonb,double precision,double precision) from public;
grant execute on function public.create_delivery_order(uuid,text,text,text,text,jsonb,double precision,double precision) to anon,authenticated;

create or replace function public.public_track_order(p_token uuid)
returns table(order_id uuid,restaurant_name text,customer_name text,total numeric,status text,driver_name text,latitude double precision,longitude double precision,recorded_at timestamptz)
language sql security definer set search_path=public
as $$
  select o.id,r.name,o.customer_name,o.total,o.status,d.name,dl.latitude,dl.longitude,dl.recorded_at
  from public.orders o
  join public.restaurants r on r.id=o.restaurant_id
  left join public.delivery_orders dox on dox.order_id=o.id
  left join public.drivers d on d.id=dox.driver_id
  left join lateral (select l.latitude,l.longitude,l.recorded_at from public.driver_locations l where l.order_id=o.id order by l.recorded_at desc limit 1) dl on true
  where o.tracking_token=p_token limit 1;
$$;
revoke all on function public.public_track_order(uuid) from public;
grant execute on function public.public_track_order(uuid) to anon,authenticated;

create or replace function public.driver_get_orders(p_token uuid)
returns table(id uuid,customer_name text,customer_phone text,address text,total numeric,status text,customer_lat double precision,customer_lng double precision,delivery_status text)
language sql security definer set search_path=public
as $$
  select o.id,o.customer_name,o.customer_phone,o.address,o.total,o.status,o.customer_lat,o.customer_lng,dox.status
  from public.drivers d join public.delivery_orders dox on dox.driver_id=d.id join public.orders o on o.id=dox.order_id
  where d.access_token=p_token and d.active=true order by o.created_at desc;
$$;
revoke all on function public.driver_get_orders(uuid) from public;
grant execute on function public.driver_get_orders(uuid) to anon,authenticated;

create or replace function public.driver_update_status(p_token uuid,p_order_id uuid,p_status text)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_driver_id uuid; v_restaurant_id uuid;
begin
  select id,restaurant_id into v_driver_id,v_restaurant_id from public.drivers where access_token=p_token and active=true;
  if v_driver_id is null then raise exception 'invalid_driver'; end if;
  if p_status not in ('accepted','picked_up','out_for_delivery','delivered','cancelled') then raise exception 'invalid_status'; end if;
  update public.delivery_orders set status=p_status,
    accepted_at=case when p_status='accepted' then coalesce(accepted_at,now()) else accepted_at end,
    picked_up_at=case when p_status='picked_up' then coalesce(picked_up_at,now()) else picked_up_at end,
    delivered_at=case when p_status='delivered' then coalesce(delivered_at,now()) else delivered_at end,
    updated_at=now()
  where order_id=p_order_id and driver_id=v_driver_id and restaurant_id=v_restaurant_id;
  if not found then raise exception 'order_not_assigned'; end if;
  update public.orders set status=case when p_status='accepted' then 'assigned' when p_status in ('picked_up','out_for_delivery') then 'out_for_delivery' when p_status='delivered' then 'delivered' when p_status='cancelled' then 'cancelled' else status end
  where id=p_order_id and restaurant_id=v_restaurant_id;
  return true;
end;
$$;
revoke all on function public.driver_update_status(uuid,uuid,text) from public;
grant execute on function public.driver_update_status(uuid,uuid,text) to anon,authenticated;

create or replace function public.driver_update_location(p_token uuid,p_order_id uuid,p_latitude double precision,p_longitude double precision,p_accuracy double precision default null)
returns boolean language plpgsql security definer set search_path=public
as $$
declare v_driver_id uuid; v_restaurant_id uuid;
begin
  select id,restaurant_id into v_driver_id,v_restaurant_id from public.drivers where access_token=p_token and active=true;
  if v_driver_id is null then raise exception 'invalid_driver'; end if;
  if p_latitude not between -90 and 90 or p_longitude not between -180 and 180 then raise exception 'invalid_coordinates'; end if;
  if not exists(select 1 from public.delivery_orders where order_id=p_order_id and driver_id=v_driver_id and restaurant_id=v_restaurant_id) then raise exception 'order_not_assigned'; end if;
  insert into public.driver_locations(restaurant_id,driver_id,order_id,latitude,longitude,accuracy) values(v_restaurant_id,v_driver_id,p_order_id,p_latitude,p_longitude,p_accuracy);
  return true;
end;
$$;
revoke all on function public.driver_update_location(uuid,uuid,double precision,double precision,double precision) from public;
grant execute on function public.driver_update_location(uuid,uuid,double precision,double precision,double precision) to anon,authenticated;

do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='orders') then alter publication supabase_realtime add table public.orders; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='delivery_orders') then alter publication supabase_realtime add table public.delivery_orders; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='driver_locations') then alter publication supabase_realtime add table public.driver_locations; end if;
end $$;

select (select count(*) from public.drivers) as drivers,(select count(*) from public.delivery_orders) as delivery_orders,(select count(*) from public.driver_locations) as gps_points,(select count(*) from public.orders where tracking_token is not null) as trackable_orders;
